-- optimize for query 1
RUNSTATS ON TABLE "DB2INST1"."LINEITEM" WITH DISTRIBUTION ON COLUMNS ( "L_SHIPDATE" NUM_FREQVALUES 15 NUM_QUANTILES 25 ) AND SAMPLED DETAILED INDEXES ALL ALLOW WRITE ACCESS;

CREATE INDEX query1index ON LINEITEM(l_returnflag ASC,l_linestatus ASC);

-- optimize for query 2
CREATE INDEX "DB2INST1"."IDX401111030170000" ON "DB2INST1"."PART"
   ("P_SIZE" ASC, "P_MFGR" ASC, "P_TYPE" ASC, "P_PARTKEY"
   ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

CREATE UNIQUE INDEX "DB2INST1"."IDX401111030090000"
   ON "DB2INST1"."PARTSUPP" ("PS_PARTKEY" ASC, "PS_SUPPKEY"
   ASC) INCLUDE ("PS_SUPPLYCOST") ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

CREATE UNIQUE INDEX "DB2INST1"."IDX401111029540000"
   ON "DB2INST1"."SUPPLIER" ("S_SUPPKEY" ASC) INCLUDE
   ("S_NATIONKEY") ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

CREATE INDEX "DB2INST1"."IDX401111029440000" ON "DB2INST1"."REGION"
   ("R_NAME" ASC, "R_REGIONKEY" DESC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
   COMMIT WORK ;

CREATE INDEX "DB2INST1"."IDX401111029470000" ON "DB2INST1"."NATION"
   ("N_REGIONKEY" ASC, "N_NATIONKEY" ASC) ALLOW REVERSE
   SCANS COLLECT SAMPLED DETAILED STATISTICS;

-- optimize for query 3
CREATE INDEX "DB2INST1"."IDX401111040480000" ON "DB2INST1"."CUSTOMER"
   ("C_MKTSEGMENT" ASC, "C_CUSTKEY" ASC) ALLOW REVERSE
   SCANS COLLECT SAMPLED DETAILED STATISTICS;

-- optimize for query 4
CREATE INDEX "DB2INST1"."ORDERKEYINDEX_SUBQUERY" ON "DB2INST1"."LINEITEM"
   ("L_ORDERKEY" ASC, L_COMMITDATE ASC, L_RECEIPTDATE ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

-- optimize for query 5
CREATE UNIQUE INDEX "DB2INST1"."IDX401111052210000"
   ON "DB2INST1"."CUSTOMER" ("C_CUSTKEY" ASC) INCLUDE
   ("C_NATIONKEY") ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
CREATE INDEX "DB2INST1"."IDX401111052230000" ON "DB2INST1"."NATION"
   ("N_REGIONKEY" ASC, "N_NAME" ASC, "N_NATIONKEY" ASC)
   ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
CREATE INDEX "DB2INST1"."IDX401111051340000" ON "DB2INST1"."SUPPLIER"
   ("S_NATIONKEY" ASC, "S_SUPPKEY" ASC) ALLOW REVERSE
   SCANS COLLECT SAMPLED DETAILED STATISTICS;
CREATE INDEX "DB2INST1"."IDX401111052280000" ON "DB2INST1"."LINEITEM"
   ("L_SUPPKEY" ASC, "L_DISCOUNT" ASC, "L_EXTENDEDPRICE"
   ASC, "L_ORDERKEY" ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

-- optimize for query 7
CREATE INDEX "DB2INST1"."IDX401111134020000" ON "DB2INST1"."ORDERS"
   ("O_ORDERDATE" ASC, "O_CUSTKEY" ASC, "O_ORDERKEY"
   ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
CREATE INDEX "DB2INST1"."IDX401111133130000" ON "DB2INST1"."PART"
   ("P_TYPE" ASC, "P_PARTKEY" ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
CREATE INDEX "DB2INST1"."IDX401111134290000" ON "DB2INST1"."LINEITEM"
   ("L_PARTKEY" ASC, "L_DISCOUNT" ASC, "L_EXTENDEDPRICE"
   ASC, "L_ORDERKEY" ASC, "L_SUPPKEY" ASC) ALLOW REVERSE
   SCANS COLLECT SAMPLED DETAILED STATISTICS;
   COMMIT WORK ;

-- optimize for query 11
CREATE INDEX "DB2INST1"."IDX401111153190000" ON "DB2INST1"."SUPPLIER"
   ("S_NATIONKEY" ASC, "S_SUPPKEY" DESC) ALLOW REVERSE
   SCANS COLLECT SAMPLED DETAILED STATISTICS;   
CREATE INDEX "DB2INST1"."IDX401111153480000" ON "DB2INST1"."PARTSUPP"
   ("PS_SUPPKEY" ASC, "PS_AVAILQTY" ASC, "PS_SUPPLYCOST"
   ASC, "PS_PARTKEY" ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

-- optimize for query 18
CREATE UNIQUE INDEX "DB2INST1"."IDX401111200340000"
   ON "DB2INST1"."ORDERS" ("O_ORDERKEY" ASC) INCLUDE
   ("O_TOTALPRICE", "O_ORDERDATE", "O_CUSTKEY") ALLOW
   REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
CREATE UNIQUE INDEX "DB2INST1"."IDX401111200320000"
   ON "DB2INST1"."CUSTOMER" ("C_CUSTKEY" ASC) INCLUDE
   ("C_NAME") ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
CREATE INDEX "DB2INST1"."QUANTITY_SUM_SUBQUERY" ON "DB2INST1"."LINEITEM"
   (L_ORDERKEY ASC, L_QUANTITY ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

-- optimize for query 21
CREATE INDEX "DB2INST1"."IDX401111211220000" ON "DB2INST1"."ORDERS"
   ("O_ORDERSTATUS" ASC, "O_ORDERKEY" ASC) ALLOW REVERSE
   SCANS COLLECT SAMPLED DETAILED STATISTICS;
CREATE INDEX "DB2INST1"."IDX401111211390000" ON "DB2INST1"."SUPPLIER"
   ("S_NATIONKEY" ASC, "S_NAME" ASC, "S_SUPPKEY" ASC)
   ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
CREATE INDEX "DB2INST1"."IDX401111211320000" ON "DB2INST1"."LINEITEM"
   ("L_SUPPKEY" ASC, "L_LINENUMBER" ASC, "L_COMMITDATE"
   ASC, "L_RECEIPTDATE" ASC, "L_ORDERKEY" ASC) ALLOW
   REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
CREATE INDEX "DB2INST1"."IDX401111211330000" ON "DB2INST1"."LINEITEM"
   ("L_ORDERKEY" ASC, "L_SUPPKEY" ASC, "L_COMMITDATE"
   ASC, "L_RECEIPTDATE" ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

-- optimize for query 22
CREATE INDEX "DB2INST1"."IDX401111208050000" ON "DB2INST1"."CUSTOMER"
   ("C_ACCTBAL" ASC, "C_CUSTKEY" ASC, "C_PHONE" ASC)
   ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
